name: flutter_templete
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  animate_do: ^2.0.0
  carousel_slider: ^4.0.0
  dio: ^4.0.0
  # firebase_messaging: ^10.0.8
  flutter_spinkit: ^5.1.0
  get: ^4.3.8
  get_storage: ^2.0.3
  intl: ^0.17.0
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_staggered_animations: "^1.0.0"
  flutter_overlay_loader: ^1.0.3

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon/flutter.png"

flutter_native_splash:
  color: "#E4F5D9"
  image: assets/images/app_icon/flutter.png

flutter:

  uses-material-design: true
  assets:
    - assets/images/app_icon/
    - assets/images/

  fonts:
    - family: Josefin
      fonts:
        - asset: assets/fonts/Medium.ttf
        - asset: assets/fonts/Light.ttf
          weight: 200
        - asset: assets/fonts/Bold.ttf
          weight: 700
